databases:
  - name: user_management
    databaseName: user_management
    user: user_management

services:
  - type: web
    name: user_management
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn user_management.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: user_management
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4